### ISSUE TITLE
can you provide more musicxml file to test this model?

### ISSUE THREAD

**Issue by daxiangpanda** [NVIDIA/mellotron#12]
can you provide more musicxml file to test this model?

**Comment by rafaelvalle** [comment]
We recently added Mozart's Kyrie Eleison from the Requiem and the demo on Debussy's.

**Comment by daxiangpanda** [comment]
can you share the xml file?

**Comment by rafaelvalle** [comment]
https://github.com/NVIDIA/mellotron/tree/master/data

**Comment by daxiangpanda** [comment]
thanks

**Comment by Liujingxiu23** [comment]
The musicxml examples are almost music (instruments) with little human voice (singing),  where can I download musicxml files of sings, for example Justin Bieber's or Adele's. Can you provide one or two examples?

**Comment by BlazJurisic** [comment]
I tried to use .musicxml file generated with musescore software without success.

**Comment by mepc36** [comment]
> I tried to use .musicxml file generated with musescore software without success.

I also tried to generate .musicxml files using Sibelius software. It also didn't work.

Did anyone ever find a tool to do this? I'm even having trouble changing the provided .musicxml files in small but noticeable ways to test them without breaking mellotron inference.
