### ISSUE TITLE
Sampling rate used for pretrained model of LibriTTS

### ISSUE THREAD

**Issue by hash2430** [NVIDIA/mellotron#17]
Hello,
I would like to ask about the hparmas used for the LibriTTS pretrained model.
The default hparams.py seems to be written for the LJSpeech DB.
So it would be appreciated if you could share the hparams you used for the pretrained LibriTTS model.
Especially, the sampling rate is set as 22050 on hparams while the wavfile.read() returns the sampling rate of 24000, resulting an assert.
Changing this is no problem but I would like to know on what sampling rate, the pretrained model is trained.
Thanks :D

**Comment by rafaelvalle** [comment]
We resampled LibriTTS to 22050Hz for training.
