### ISSUE TITLE
Yin pitch set to minimum 100 Hz

### ISSUE THREAD

**Issue by drfeinberg** [NVIDIA/mellotron#19]
Your Yin Pitch algorithm pitch minimum is set to 100 Hz, so you can't use any voices lower than that threshold.  To lower it, you'll also need to make the window size larger to accommodate the lower frequencies.

**Comment by rafaelvalle** [comment]
https://github.com/NVIDIA/mellotron/blob/master/hparams.py

**Comment by drfeinberg** [comment]
Sorry I missed that. Thanks.
