### ISSUE TITLE
long dataset need more  video memory？

### ISSUE THREAD

**Issue by daxiangpanda** [NVIDIA/mellotron#21]
train this model with a longer dataset（10s to 20s per audio）.I noticed that batch size is smaller than when I trained with LJSpeech dataset.

**Comment by rafaelvalle** [comment]
You can use longer files but you will need to decrease the batch size.
For each batch, the data loader zero pads the data in that batch to the length of the longest sample.

**Comment by daxiangpanda** [comment]
I train this model with a p40 GPU with my own dataset.

**Comment by rafaelvalle** [comment]
Adjust the batch size to fit your memory availability.

**Comment by daxiangpanda** [comment]
thx
