### ISSUE TITLE
hparams trainings settings

### ISSUE THREAD

**Issue by peter1000** [NVIDIA/mellotron#26]
Hi,

refering to your paper:

```
4.1. Training Setup
 For all the experiments, we trained on LJS, Sally and the
train-clean-100 subset of LibriTTS with over 100 speakers
and 25 minutes on average per speaker.

```
I'd be interested in knowing if you use the same training settings for all 3 *(LJS, Sally and the train-clean-100 subset of LibriTTS)*

did you just change the training_files, validation_files path or many of the other parameters too?

https://github.com/NVIDIA/mellotron/blob/master/hparams.py#L5

THANKS

**Comment by rafaelvalle** [comment]
We also changed the number of speakers: https://github.com/NVIDIA/mellotron/blob/master/hparams.py#L88

**Comment by peter1000** [comment]
Thanks very kind of you taking the time to reply
