### ISSUE TITLE
LJS trained model?

### ISSUE THREAD

**Issue by scottbouma** [NVIDIA/mellotron#32]
Thank you so much for sharing this!  I have it working on Google Colab (thanks to @yhgon ).  But I cannot find the pretrained LJS model which you mentioned on your website (https://nv-adlr.github.io/Mellotron).  Can you post a download link to your LJS model?  Thanks!

**Comment by rafaelvalle** [comment]
We do not have a model trained only on LJS.
You can use the model trained on LibriTTS: https://drive.google.com/file/d/1ZesPPyRRKloltRIuRnGZ2LIUEuMSVjkI/view

**Comment by rafaelvalle** [comment]
We uploaded a model trained on LJS.
Please take a look at our README!
