### ISSUE TITLE
Training DB for Waveglow pretrained model in this repo

### ISSUE THREAD

**Issue by hash2430** [NVIDIA/mellotron#37]
Hello,
May I ask what database is used for training the pretrained waveglow model whose link is attached in the ReadMe of this repo?
I searched [Nvidia GPU Cloud](https://ngc.nvidia.com/catalog/models?orderBy=modifiedDESC&query=waveglow&quickFilter=&filters=) to see if I can find description on this pretrained model but pretrained Waveglow checkpoints on that repo was only on single speaker (LJSpeech).
I don't think the pretrained waveglow that is refered to in this repo is trained on single speaker though. 
Thanks!

**Comment by rafaelvalle** [comment]
The WaveGlow linked in the readme was trained on a single speaker with proprietary studio quality data. This suggests that WaveGlow is an universal decoder.

**Comment by hash2430** [comment]
Wow. Thanks. I'm surprised to hear how universer it can be. That's good to know :D

**Comment by rafaelvalle** [comment]
Spread the word :-)
