### ISSUE TITLE
Singing voice from audio signal

### ISSUE THREAD

**Issue by tebin** [NVIDIA/mellotron#38]
The inference notebook has examples on rhythm/pitch transfer and singing voice from music score, but there is no explanation as to how to synthesize singing voice from audio signal, which is presented on [https://nv-adlr.github.io/Mellotron](url). Is this feature not supported?

**Comment by rafaelvalle** [comment]
The feature is supported: singing voice from audio signal is similar to rhythm and pitch transfer.

**Comment by tebin** [comment]
Thanks for the reply. Now that I know I have to expand upon the rhythm/pitch transfer example, I have some follow-up questions.

1. The paper states that "the target speaker, St, would always be found in the training set, while the source text, pitch and rhythm (Ts, Ps, Rs) could be from outside the training set." so I presume there is no need for speaker ids for source audios - it doesn't make sense after all for some arbitrary input audio outside the training set to have a valid speaker id. However in the examples_filelist.txt there is a column for speaker ids. What is the significance of this column?

2. The demo website has an example of synthesizing an Indian song using Mellotron LJS and Mellotron Sally. How is it possible to feed Indian text into the models that were trained on English datasets?

**Comment by rafaelvalle** [comment]
1. The model expects a speaker id, so we give it a random speaker id.

2. The model is also trained on phoneme representations called arpabet.
During inference one can chose those that match the phonemes in the source
audio.
