### ISSUE TITLE
Generic Inference

### ISSUE THREAD

**Issue by CookiePPP** [NVIDIA/mellotron#4]
I'm trying to perform inference without a file for copying style from, just using this repo like a multi-speaker Tacotron2 without GSTs.
What code do I need for that?

In Tacotron2 you only need the Text Input to use tacotron.inference but I'm not sure how to do inference here where I just input,
Text, SpeakerID.

Your notebook has 2 examples of "tacotron.inference_noattention" and how to get the inputs for them, but no examples for just "tacotron.inference", and I'm having trouble telling from the source code.

**Comment by rafaelvalle** [comment]
https://github.com/NVIDIA/mellotron/blob/master/model.py#L611
It takes text, style_input (mel or int), speaker_ids, f0s

**Comment by CookiePPP** [comment]
I noticed, what should f0s be when I'm trying to generate new audio without a reference?

**Comment by blisc** [comment]
You can simply pass in a vector of 0s for f0 if you want your model to predict it instead of specifying it. You'd probably have to play around with the shape of the vector but its size should be your batch size.

**Comment by CookiePPP** [comment]
Alright, I'll give that a shot. Thanks

**Comment by blackmamba1122** [comment]
> You can simply pass in a vector of 0s for f0 if you want your model to predict it instead of specifying it. You'd probably have to play around with the shape of the vector but its size should be your batch size.

Hi, I'm trying to inference with the mellotron modrand waveglow models. can you tell me the size of the shape is f0s, which is a vector of 0s?

**Comment by blackmamba1122** [comment]
> You can simply pass in a vector of 0s for f0 if you want your model to predict it instead of specifying it. You'd probably have to play around with the shape of the vector but its size should be your batch size.

Hi, I'm trying to inference with the mellotron model and waveglow model. can you tell me the size of the shape of f0s, which is a vector of 0s?
