### ISSUE TITLE
Warning Message in yin

### ISSUE THREAD

**Issue by pneumoman** [NVIDIA/mellotron#47]
For some of my audio I'm getting a warning message:

> yin.py:44: RuntimeWarning: invalid value encountered in true_divide
> cmndf = df[1:] * range(1,N) / np.cumsum(df[1:]).stype(float) #scipy method

Any ideas?  The problem children are encoded exactly like their peers.

Thanks

**Comment by aijianiula0601** [comment]
I got the same error.

**Comment by rasenganai** [comment]
Same warning

**Comment by jinny1208** [comment]
> For some of my audio I'm getting a warning message:
> 
> > yin.py:44: RuntimeWarning: invalid value encountered in true_divide
> > cmndf = df[1:] * range(1,N) / np.cumsum(df[1:]).stype(float) #scipy method
> 
> Any ideas? The problem children are encoded exactly like their peers.
> 
> Thanks

Did you solve the problem? If so, may I ask how you did so? If not, did you ignore the warning and continue training? How were the results?

**Comment by pneumoman** [comment]
My impression is that this is caused by the whole window segment being silence.  I think I may have fixed this by just adding a little offset to the denominator to keep it from being a true zero.  The other approach is to curate your dataset to remove any excess silence from your recordings

**Comment by jinny1208** [comment]
> My impression is that this is caused by the whole window segment being silence. I think I may have fixed this by just adding a little offset to the denominator to keep it from being a true zero. The other approach is to curate your dataset to remove any excess silence from your recordings

Thank you. Adding offset to the denominator got rid of the warning.
