### ISSUE TITLE
Synthesized voice does not correspond to the speaker id

### ISSUE THREAD

**Issue by paarthneekhara** [NVIDIA/mellotron#54]
I was using the inference notebook with the pre-trained models. I noticed that the synthesized audio does not always correspond to the speaker id. For many male speakers, the audio still sounds like that from a female speaker. I tried using both the inference function and inference_noattention functions. Is this an issue faced by anyone else?

**Comment by Sangkikim-77** [comment]
Hi,

Training using a pre-trained model can lead to faster convergence
By default, the speaker embedding layer is **ignored**

**Comment by magictron** [comment]
the pre-trained model does have speaker embedding as you can load the model and see that layer.
But it does seem to be quite picth/rythm related. you can try to extract pitch and rythm from a different wav to see/test

**Comment by paarthneekhara** [comment]
Nevermind, I think there was a bug in loading the speaker dictionary in the inference on my end. Although for some speakers, the voice does not quite match the data. Maybe because of fewer corresponding speaker samples during training.

**Comment by deepuvikraman** [comment]
@paarthneekhara - I am also facing this similar issue. I am using libritts pretrained model and trying to generate voice for a custom text using a reference style wav file. Though I specify a different speake_rid (in the example_filelists.txt along with style wav, its transcript), the voice generated is always same of a female voice. Do you know how to generate voice of a different speaker that is present in the pre-trained model?
