### ISSUE TITLE
ReferenceEncoder did not use the actual mel lengths

### ISSUE THREAD

**Issue by hubeibei007** [NVIDIA/mellotron#71]
In the ReferenceEncoder, it only use the mels as inputs. When training or batch inference, the mels are padded_data, it seems that the ReferenceEncoder should use the actual mel lengths to get the last GRU hidden state. Please correct me if any wrong understandings. 

Add my test results. when ReferenceEncoder get the last hidden state by pack_padded_sequence, in my dataset the clusters of style tokens are more clear than without pack_padded_sequence.

**Comment by rafaelvalle** [comment]
Can you share the location in code?

**Comment by hubeibei007** [comment]
OK, I will prepare and submit a pull request.
