### ISSUE TITLE
Strange query input shape of multihead attention in STL

### ISSUE THREAD

**Issue by elch10** [NVIDIA/mellotron#77]
When I try `melltoron` with different hparams found strange line in STL module:
https://github.com/NVIDIA/mellotron/blob/master/modules.py#L94
```python
d_q = hp.token_embedding_size // 2
```
So, in hparams file I found that `ref_enc_gru_size` is half of `token_embedding_size`, so all work normally without changing hparams: https://github.com/NVIDIA/mellotron/blob/master/hparams.py#L97 
But If you try to change `ref_enc_gru_size` to another value script will raise error.
Right shape is:
```python
d_q = hp.ref_enc_gru_size
```

**Comment by rafaelvalle** [comment]
Good catch, thank you!
